### ISSUE TITLE
Аудит системы голосования

### ISSUE THREAD

**Issue by frenzykryger** [moscow-technologies/blockchain-voting#22]
Был-ли проведен аудит данной системы голосования силами ФСТЭК или другой гос. организации отвечающей за надзор в сфере ИБ перед фактической разверткой системы в прод?

**Comment by wolframdeus** [comment]
@frenzykryger в [8 пункте](https://meduza.io/cards/kriptograf-vzlomal-sistemu-internet-golosovaniya-v-moskve-my-tozhe-eto-sdelali-i-vy-tozhe-mozhete) утверждается, что да, ФСТЭК, ФСБ и даже военные хакеры из ГРУ!)

**Comment by monich** [comment]
Поскольку государство здесь - заинтересованная сторона, настоящий аудит должен проводится силами организаций и частных лиц, независимых от государства. И уж точно не ФСБ и не ГРУ.

**Comment by frenzykryger** [comment]
Ну если аудит был то можно закрывать ишую. У меня возникли сомнения по этому поводу т.к. я не увидел юнит тестов и интеграционных тестов исключая базовый на шифровку\расшифровку который лежит отдельно.
