### ISSUE TITLE
Hacked secret keys and messages

### ISSUE THREAD

**Issue by RomanIovlev** [moscow-technologies/blockchain-voting#3]
https://meduza.io/cards/kriptograf-vzlomal-sistemu-internet-golosovaniya-v-moskve-my-tozhe-eto-sdelali-i-vy-tozhe-mozhete
#допускай #отпускай

**Comment by kabus1917** [comment]
Собянина в отставку!

**Comment by stepbyst3p** [comment]
Хватит работать на мудаков!

**Comment by a-borodenkov** [comment]
Замечания, данные в статье учтены. Подробнее можно ознакомиться по ссылке https://ria.ru/20190815/1557554631.html
